# Generated by Django 5.2.4 on 2025-07-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("task_description", models.TextField()),
            ],
        ),
    ]
